import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
const products = [
  {id:'hp-001',name:'AeroBeat ANC 40',brand:'AeroBeat',category:'Headphones',price:4299,originalPrice:5999,discount:28,rating:4.5,reviewCount:1842,description:'Travel-focused wireless headphones with active noise cancellation and long battery life.',specifications:{battery:'40 hours',anc:'Hybrid ANC',weight:'245g',codec:'AAC'},features:['Hybrid ANC','40-hour battery','Foldable','USB-C fast charge'],stock:24,image:'headphones',tags:['travel','anc','battery','wireless']},
  {id:'hp-002',name:'SonicPulse Pro',brand:'SonicPulse',category:'Headphones',price:4899,originalPrice:6499,discount:25,rating:4.7,reviewCount:2310,description:'Premium over-ear headphones tuned for detail, comfort and commuting.',specifications:{battery:'50 hours',anc:'Adaptive ANC',weight:'238g',codec:'LDAC'},features:['Adaptive ANC','50-hour battery','LDAC','Multipoint'],stock:18,image:'headphones',tags:['travel','anc','premium','ldac']},
  {id:'hp-003',name:'CloudSound Lite',brand:'CloudSound',category:'Headphones',price:3199,originalPrice:3999,discount:20,rating:4.3,reviewCount:1176,description:'Lightweight wireless headphones with strong battery life and balanced sound.',specifications:{battery:'45 hours',anc:'ENC calls',weight:'198g',codec:'AAC'},features:['45-hour battery','198g lightweight','Clear calls','Foldable'],stock:32,image:'headphones',tags:['travel','lightweight','battery']},
  {id:'hp-004',name:'BassForge X',brand:'BassForge',category:'Headphones',price:3799,originalPrice:4999,discount:24,rating:4.4,reviewCount:965,description:'Bass-forward ANC headphones with a comfortable fit for long listening sessions.',specifications:{battery:'36 hours',anc:'Hybrid ANC',weight:'260g',codec:'AAC'},features:['Hybrid ANC','36-hour battery','Deep bass','Comfort cushions'],stock:14,image:'headphones',tags:['bass','anc','comfort']},
  {id:'ph-001',name:'Nova X5 5G',brand:'Nova',category:'Smartphones',price:27999,originalPrice:32999,discount:15,rating:4.6,reviewCount:3410,description:'Balanced 5G phone with a 50MP camera, bright display and all-day battery.',specifications:{camera:'50MP OIS',display:'120Hz AMOLED',battery:'5000mAh',ram:'8GB'},features:['50MP OIS','120Hz AMOLED','5000mAh','5G'],stock:16,image:'phone',tags:['camera','5g','amoled','battery']},
  {id:'ph-002',name:'PixelPeak 8a',brand:'PixelPeak',category:'Smartphones',price:29999,originalPrice:34999,discount:14,rating:4.7,reviewCount:2988,description:'Compact camera-first smartphone with computational photography and clean software.',specifications:{camera:'64MP OIS',display:'120Hz OLED',battery:'4600mAh',ram:'8GB'},features:['64MP OIS','AI camera','120Hz OLED','Wireless charging'],stock:11,image:'phone',tags:['camera','ai','compact','oled']},
  {id:'ph-003',name:'VoltOne Max',brand:'VoltOne',category:'Smartphones',price:24999,originalPrice:28999,discount:14,rating:4.4,reviewCount:1850,description:'Performance-oriented 5G phone with fast charging and a large display.',specifications:{camera:'50MP',display:'144Hz AMOLED',battery:'5500mAh',ram:'12GB'},features:['12GB RAM','144Hz AMOLED','5500mAh','80W charging'],stock:20,image:'phone',tags:['gaming','battery','performance','5g']},
  {id:'lap-001',name:'SlateBook Air 14',brand:'Slate',category:'Laptops',price:64999,originalPrice:74999,discount:13,rating:4.6,reviewCount:874,description:'Slim productivity laptop with a color-accurate display and long battery life.',specifications:{cpu:'Core Ultra 5',ram:'16GB',storage:'512GB SSD',display:'14-inch 2.8K'},features:['16GB RAM','512GB SSD','2.8K display','12-hour battery'],stock:8,image:'laptop',tags:['student','productivity','lightweight']},
  {id:'lap-002',name:'ForgeBook 15',brand:'Forge',category:'Laptops',price:71999,originalPrice:79999,discount:10,rating:4.5,reviewCount:612,description:'Powerful laptop for development, editing and demanding multitasking.',specifications:{cpu:'Ryzen 7',ram:'16GB',storage:'1TB SSD',display:'15.6-inch 144Hz'},features:['Ryzen 7','16GB RAM','1TB SSD','144Hz display'],stock:6,image:'laptop',tags:['coding','performance','editing']},
  {id:'sw-001',name:'PulseWatch 3',brand:'Pulse',category:'Smartwatches',price:6999,originalPrice:8999,discount:22,rating:4.4,reviewCount:1503,description:'Everyday smartwatch with AMOLED display, GPS and multi-day battery.',specifications:{display:'1.8 AMOLED',battery:'10 days',gps:'Built-in',water:'5ATM'},features:['AMOLED','GPS','10-day battery','5ATM'],stock:22,image:'watch',tags:['fitness','gps','battery']},
  {id:'ac-001',name:'VoltCharge 65W GaN',brand:'VoltCharge',category:'Accessories',price:799,originalPrice:999,discount:20,rating:4.6,reviewCount:2104,description:'Compact 65W GaN charger for phones, tablets and compatible laptops.',specifications:{power:'65W',ports:'2 USB-C + 1 USB-A',weight:'112g',standard:'PD 3.0'},features:['65W PD','GaN compact','3 ports','Travel friendly'],stock:40,image:'charger',tags:['charger','travel','usb-c','accessory']},
  {id:'ac-002',name:'AirTag Travel Case',brand:'Trail',category:'Accessories',price:399,originalPrice:499,discount:20,rating:4.2,reviewCount:744,description:'Compact protective tracker case for bags and luggage.',specifications:{material:'Silicone',fit:'Universal',weight:'18g'},features:['Lightweight','Luggage ready','Scratch protection'],stock:60,image:'case',tags:['travel','luggage','accessory']}
]
async function main(){
  for(const p of products) await prisma.product.upsert({where:{id:p.id},update:p,create:p})
  console.log(`Seeded ${products.length} products`)
}
main().finally(()=>prisma.$disconnect())
