'use client'
import {useEffect,useMemo,useState} from 'react'
import type {CartItem,Product} from '@/types'

const money=(n:number)=>`₹${n.toLocaleString('en-IN')}`
const icon=(x:string)=>({headphones:'🎧',phone:'📱',laptop:'💻',watch:'⌚',charger:'🔌',case:'🧳'} as any)[x]||'🛍️'

type Msg={role:'user'|'agent';text:string;products?:Product[];comparison?:Product[];action?:string}
type AuditEvent={time:string;label:string;detail:string;status:'approved'|'info'|'success'|'blocked'}
export default function Home(){
 const [messages,setMessages]=useState<Msg[]>([{role:'agent',text:'Welcome to CartPilot. Tell me what you want to buy, your budget, and any must-have features. I can search, compare, manage your cart and prepare checkout.'}])
 const [input,setInput]=useState('')
 const [cart,setCart]=useState<CartItem[]>([])
 const [checkout,setCheckout]=useState(false)
 const [paying,setPaying]=useState(false)
 const [demoPayment,setDemoPayment]=useState<'open'|'success'|null>(null)
 const [audit,setAudit]=useState<AuditEvent[]>([])
 const auditLog=(label:string,detail:string,status:AuditEvent['status']='info')=>setAudit(a=>[{time:new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}),label,detail,status},...a].slice(0,10))
 useEffect(()=>{ const script=document.createElement('script'); script.src='https://checkout.razorpay.com/v1/checkout.js'; script.async=true; document.body.appendChild(script); return()=>{script.remove()} },[])
 const subtotal=useMemo(()=>cart.reduce((n,x)=>n+x.price*x.quantity,0),[cart])
 const discount=subtotal>=5000?Math.round(subtotal*.10):0
 const total=subtotal-discount
 const send=async(text=input.trim())=>{if(!text)return;auditLog('User request',text,'info');setMessages(m=>[...m,{role:'user',text}]);setInput('');try{const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,cart})});const r=await res.json();if(!res.ok)throw new Error(r.error||'Agent request failed');if(r.cart)setCart(r.cart);if(r.action)auditLog('Agent action',r.text||r.action,r.action==='checkout'?'approved':'success');setMessages(m=>[...m,{role:'agent',text:r.text||'Done.',products:r.products,comparison:r.comparison,action:r.action}]);if(r.action==='checkout')setCheckout(true)}catch(e){setMessages(m=>[...m,{role:'agent',text:`I couldn't complete that action: ${e instanceof Error?e.message:'Unknown error'}.`}] )}}
 const add=(p:Product)=>{auditLog('Cart update',`Added ${p.name} · ${money(p.price)}`,'approved');const idx=cart.findIndex(x=>x.id===p.id);setCart(idx>=0?cart.map((x,i)=>i===idx?{...x,quantity:x.quantity+1}:x):[...cart,{...p,quantity:1}])}
 const change=(id:string,d:number)=>{const item=cart.find(x=>x.id===id);if(item)auditLog('Cart update',`${d>0?'Increased':'Decreased'} ${item.name} quantity`,'approved');setCart(c=>c.map(x=>x.id===id?{...x,quantity:x.quantity+d}:x).filter(x=>x.quantity>0))}
 const completeDemoPayment=()=>{auditLog('Payment gate','Demo payment explicitly approved by user · no real charge','success');setDemoPayment('success');setMessages(m=>[...m,{role:'agent',text:'Demo payment completed successfully. No real money was charged. The checkout handoff is ready for Razorpay Test Mode once backend credentials are configured.',action:'demo_payment_verified'}])}
 return <main className="shell">
  {demoPayment&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="CartPilot test checkout"><div className="payment-modal"><div className="payment-head"><div><div className="payment-brand"><span className="payment-mark">CP</span> CartPilot</div><div className="payment-sub">Secure Test Checkout</div></div><button className="modal-close" onClick={()=>setDemoPayment(null)} aria-label="Close">×</button></div>{demoPayment==='open'?<><div className="payment-amount"><span>Amount to pay</span><strong>{money(total)}</strong></div><div className="test-banner"><b>TEST MODE SIMULATION</b><span>No real payment will be processed.</span></div><div className="method-list"><div className="method active"><span>UPI</span><small>Instant test payment</small><b>›</b></div><div className="method"><span>Card</span><small>Test card checkout</small><b>›</b></div><div className="method"><span>Netbanking</span><small>Test banking flow</small><b>›</b></div></div><div className="payment-note">This screen is a local demo fallback because Razorpay Test API credentials are not configured. It does <b>not</b> represent a Razorpay transaction.</div><button className="primary payment-btn" onClick={completeDemoPayment}>Simulate Successful Payment · {money(total)}</button><button className="smallbtn" onClick={()=>setDemoPayment(null)}>Cancel</button></>:<div className="payment-success"><div className="success-icon">✓</div><h3>Payment Successful</h3><p>{money(total)} demo payment completed.</p><div className="receipt"><div><span>Status</span><b>Verified (Demo)</b></div><div><span>Order</span><b>CP-DEMO-{Date.now().toString().slice(-6)}</b></div><div><span>Gateway</span><b>Simulation</b></div></div><div className="payment-note">No money was charged. In a configured environment, this same handoff opens Razorpay Test Mode and the server verifies the payment signature.</div><button className="primary payment-btn" onClick={()=>{setDemoPayment(null);setCheckout(false)}}>Back to CartPilot</button></div>}</div></div>}

  <header className="topbar"><div className="brand"><div className="logo">CP</div><div><h1>CartPilot</h1><p>AI Agent for Autonomous Commerce</p></div></div><div className="pill">BUILDATHON MVP • DEMO MODE</div></header>
  {checkout?<div className="panel checkout"><h2>Checkout</h2><p className="muted">Review your order before payment.</p><div className="sidepanel" style={{padding:0}}>{cart.map(x=><div className="cart-item" key={x.id}><div className="miniart">{icon(x.image)}</div><div className="cart-info"><b>{x.name}</b><div className="muted">{x.quantity} × {money(x.price)}</div></div></div>)}</div><div className="stat"><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="stat"><span>AI offer</span><b>-{money(discount)}</b></div><div className="total"><span>Total</span><span>{money(total)}</span></div><div className="field"><label>Name</label><input placeholder="Demo customer"/></div><div className="field"><label>Email</label><input placeholder="demo@example.com"/></div><button className="primary" disabled={paying} onClick={async()=>{setPaying(true);try{const r=await fetch('/api/razorpay/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:cart.map(x=>({id:x.id,quantity:x.quantity}))})});const data=await r.json();if(data.demo){setDemoPayment('open');return}if(!r.ok)throw new Error(data.error||'Could not create Razorpay order');const Razorpay=(window as any).Razorpay;if(!Razorpay)throw new Error('Razorpay Checkout is still loading. Try again.');const rz=new Razorpay({key:data.keyId,amount:data.amount,currency:data.currency,name:'CartPilot',description:'CartPilot Buildathon Test Order',order_id:data.orderId,prefill:{name:'Demo customer',email:'demo@example.com'},handler:async(response:any)=>{const vr=await fetch('/api/razorpay/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(response)});const vd=await vr.json();if(vd.verified)alert('Razorpay test payment verified successfully.');else alert(vd.error||'Payment verification failed.')}});rz.open()}catch(e){alert(e instanceof Error?e.message:'Payment failed')}finally{setPaying(false)}}}>{paying?'Opening…':`Pay ${money(total)}`}</button><div className="demo">{process.env.NEXT_PUBLIC_RAZORPAY_DEMO==='false'?'Razorpay Test Mode: payment is simulated and no real money is charged.':'Demo checkout: no real payment is processed until Razorpay test credentials are configured in the backend.'}</div><button className="smallbtn" onClick={()=>setCheckout(false)}>← Back to shopping</button></div>
  :<div className="grid"><section className="panel chat"><div className="hero"><h2>Shop by telling us what you need.</h2><p>CartPilot converts natural-language intent into commerce actions: discover → compare → recommend → cart → offer → checkout.</p></div><div className="messages">{messages.map((m,i)=><div className={'msg '+m.role} key={i}><div className="bubble">{m.text}</div>{m.action&&m.action!=='checkout'&&<div className="action">● Agent action: {m.action.replaceAll('_',' ')}</div>}{m.products&&<div className="products">{m.products.map(p=><div className="product" key={p.id}><div className="product-art">{icon(p.image)}</div><h4>{p.name}</h4><div className="muted" style={{fontSize:11}}>{p.brand} • {p.category}</div><div className="rating">★ {p.rating} <span className="muted">({p.reviewCount.toLocaleString()})</span></div><div className="price">{money(p.price)}<span className="strike">{money(p.originalPrice)}</span></div><div className="tags">{p.features.slice(0,3).map(t=><span className="tag" key={t}>{t}</span>)}</div><button className="smallbtn" onClick={()=>add(p)}>Add to cart</button></div>)}</div>}{m.comparison&&<div className="compare"><table><thead><tr><th>Spec</th>{m.comparison.map(p=><th key={p.id}>{p.name}</th>)}</tr></thead><tbody>{['price','rating','battery','anc','weight'].map(k=><tr key={k}><td>{k}</td>{m.comparison!.map(p=><td key={p.id}>{k==='price'?money(p.price):k==='rating'?`★ ${p.rating}`:p.specifications[k]||'—'}</td>)}</tr>)}</tbody></table></div>}</div>)}</div><div className="composer"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="e.g. wireless headphones under ₹5,000 for travel"/><button onClick={()=>send()}>Send</button></div></section>
  <aside className="side"><div className="panel sidepanel audit-panel"><div className="audit-title"><div><h3>Agent audit trail</h3><p>Visible commerce actions · user-gated</p></div><span>{audit.length}</span></div>{audit.length===0?<p className="muted" style={{fontSize:12}}>Actions will appear here as you shop.</p>:<div className="audit-list">{audit.map((e,i)=><div className="audit-row" key={i}><span className={'audit-dot '+e.status}>✓</span><div><b>{e.label}</b><p>{e.detail}</p><small>{e.time}</small></div></div>)}</div>}</div><div className="panel sidepanel"><h3>Cart</h3>{cart.length===0?<p className="muted" style={{fontSize:12}}>Your cart is empty. Ask the agent to add something.</p>:cart.map(x=><div className="cart-item" key={x.id}><div className="miniart">{icon(x.image)}</div><div className="cart-info"><b>{x.name}</b><div>{money(x.price)} × {x.quantity}</div><div><button className="tag" onClick={()=>change(x.id,-1)}>−</button> <button className="tag" onClick={()=>change(x.id,1)}>+</button></div></div></div>)}<div className="stat"><span>Subtotal</span><b>{money(subtotal)}</b></div>{discount>0?<div className="offer">AI Growth Offer unlocked: 10% off because your cart crossed ₹5,000.</div>:subtotal>0?<div className="offer">You are {money(5000-subtotal)} away from unlocking the current 10% offer.</div>:null}<div className="total"><span>Total</span><span>{money(total)}</span></div><button className="primary" style={{width:'100%',marginTop:12}} disabled={!cart.length} onClick={()=>setCheckout(true)}>Checkout</button></div>
  <div className="panel sidepanel"><h3>Try these prompts</h3>{['I need wireless headphones under ₹5,000 for travel','Compare the first and third','Add the second one to my cart','Find a useful accessory under ₹500','Apply the best available offer','Proceed to checkout'].map(x=><button key={x} className="smallbtn" onClick={()=>{setInput(x);send(x)}}>{x}</button>)}</div><div className="panel sidepanel"><h3>Why it is agentic</h3><div className="stat"><span>Natural language</span><b>✓</b></div><div className="stat"><span>Tool-style actions</span><b>✓</b></div><div className="stat"><span>Contextual cart</span><b>✓</b></div><div className="stat"><span>Offer optimization</span><b>✓</b></div><div className="stat"><span>Checkout handoff</span><b>✓</b></div></div></aside></div>}
 </main>
}
